---
ID: "9d1d1fc1-8405-4fef-a3f1-b7ddbdb63290"
Parent: "5d7682df-27d9-4fc9-bb4e-7ac06d7bbd7c"
Template: "a2a80c92-826a-4928-beed-6e46fff31919"
Path: /sitecore/Commerce/Commerce Control Panel/Storefront Settings/Storefronts/Wooli/Fulfillment Configuration
DB: master
SharedFields:
- ID: "0452eb98-bc28-4fd8-a3b4-533f26c62705"
  Hint: Fulfillment Options
  Type: Multilist
  Value: |
    {2FB0128E-FBBD-4FCE-9197-F000D8D39F5C}
    {3817F8D5-994B-4FBC-8BBE-4C342EC7553A}
- ID: "769b63db-453f-44e6-aa90-cbc916e47f7d"
  Hint: Allow items to be delivered Individually
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Fulfillment Configuration
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171123T163853Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
