---
ID: "83758f53-2776-46a7-8684-a670f682aec9"
Parent: "5d7682df-27d9-4fc9-bb4e-7ac06d7bbd7c"
Template: "9c514ff0-fbf7-42f1-82f6-156272f70caa"
Path: /sitecore/Commerce/Commerce Control Panel/Storefront Settings/Storefronts/Wooli/Language Configuration
DB: master
SharedFields:
- ID: "03265dc1-ccfe-470d-aed1-ea9aab5b3f55"
  Hint: Language Set
  Value: "{3EC08B88-2337-4B4F-8B9B-E4C7C86FC636}"
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Language Configuration
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171123T163956Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
