---
ID: "044f856d-261f-4606-9ea4-621e84f10a85"
Parent: "bff2d09d-0b61-4b88-b60b-630d0160b4f4"
Template: "bff2d09d-0b61-4b88-b60b-630d0160b4f4"
Path: /sitecore/templates/CommerceConnect/Sitecore Commerce/Commerce Control Panel/Commerce Engine Settings/Commerce Engine Settings Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{AA15BAD2-8E72-4999-86EF-2B3F0CD1A425}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161127T132336Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
  - Version: 2
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161127T132336Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
