---
ID: "a9610f6d-b2a2-42d3-a1e7-ed3daec17074"
Parent: "06f9c316-0c4a-41bb-a603-1f7a521a1a8b"
Template: "0437fee2-44c9-46a6-abe9-28858d9fee8c"
Path: /sitecore/templates/Wooli/Feature/Catalog/Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180529T123317Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
