---
ID: "d3746db3-7cfd-426e-83ac-052a07971a0f"
Parent: "b1142e79-d313-41b1-b3c2-268ebb80c489"
Template: "b1142e79-d313-41b1-b3c2-268ebb80c489"
Path: /sitecore/templates/Wooli/Feature/Navigation/Menu Item Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{5DCCB05C-59F3-4579-AEA3-6E5DC934C7B0}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180428T090745Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
