---
ID: "ab6feece-afa4-49b8-b96d-f15e28eaefcd"
Parent: "8a4a4747-3278-437b-a12d-15d9ce6e1abf"
Template: "ab86861a-6030-46c5-b394-e8f99e8b87db"
Path: /sitecore/templates/CommerceConnect/Products/Lookup Values
DB: master
SharedFields:
- ID: "12c33f3f-86c5-43a5-aeb4-5598cec45116"
  Hint: __Base template
  Type: tree list
  Value: "{A87A00B1-E6DB-45AB-8B54-636FEC3B5523}"
- ID: "f7d48a55-2158-4f02-9356-756654404f73"
  Hint: __Standard values
  Value: "{91FB77CF-40E6-47A9-B71B-33D231135BB9}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20130516T130406
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
