---
ID: "aecafb78-3d1c-41de-a896-095dcca4a5ee"
Parent: "02303189-7dc9-41c9-914a-4784878a6a7d"
Template: "02303189-7dc9-41c9-914a-4784878a6a7d"
Path: /sitecore/templates/HCA/Feature/PageContent/Recommended Products/Recommended Products/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200519T084240Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "ba9cd774-93ea-490e-b978-38efe2c648ed"
      Hint: Header
      Value: $name
