---
ID: "a9d59828-f14d-4dbd-90d0-58f596c66ae6"
Parent: "ca4b8e4a-bfec-474a-8a85-e7df2d9c1404"
Template: "ca4b8e4a-bfec-474a-8a85-e7df2d9c1404"
Path: /sitecore/templates/Wooli/Feature/Catalog/Settings/Product Color Mapping/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180529T124637Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "ba711f5f-bc6f-4bb0-9628-1f135ec399fa"
      Hint: Color Name
      Value: $name
