---
ID: "aaff539a-7a5f-4736-ad9c-25dff75fdc12"
Parent: "334e2b54-f913-411d-b159-a7b16d65242c"
Template: "334e2b54-f913-411d-b159-a7b16d65242c"
Path: /sitecore/templates/Commerce/Catalog/Commerce Catalog Folder/__Standard Values
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Business/32x32/table_view.png
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {93AF861A-B6F4-45BE-887D-D93D4B95B39D}
    {19988B71-6F3D-43EB-8253-E6D451878922}
- ID: "d3ae7222-425d-4b77-95d8-ee33ac2b6730"
  Hint: __Context Menu
  Value: "{64BA1004-F0BE-429E-AAAD-20BD42BD99B5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20130523T143900
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
