---
ID: "73fd6747-1368-4499-bcf3-aa567fd36efe"
Parent: "5f257a2a-dfed-4617-a24a-3e85ba695305"
Template: "5f257a2a-dfed-4617-a24a-3e85ba695305"
Path: /sitecore/templates/HCA/Feature/Navigation/Header/Header Folder/__Standard Values
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: office/32x32/folder.png
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{4E6F821A-A5CC-4FD5-9AB3-F94A9A785F44}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200428T190125Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
