---
ID: "205a8529-8e9d-489c-923a-b7eeb2e9fbbd"
Parent: "3c486a78-0beb-48d9-8eb3-9a8f87b5e7e2"
Template: "3c486a78-0beb-48d9-8eb3-9a8f87b5e7e2"
Path: /sitecore/templates/HCA/Feature/PageContent/Home Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{309E5F2F-CB6F-4E51-9A39-185BE515F278}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180621T114216Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
