---
ID: "3d3c72da-de2c-48a2-9f23-7d6589477963"
Parent: "7cc3185b-6def-4d8e-bf12-d981dfd2b614"
Template: "7cc3185b-6def-4d8e-bf12-d981dfd2b614"
Path: /sitecore/templates/CommerceConnect/Sitecore Commerce/Commerce Control Panel/Shared Settings/Fulfillment/Fulfillment Option/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{79C4BB54-DF7D-4825-BFA7-32FF9B051299}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161128T122950Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "f311c61a-08dd-411a-b280-42e335ec6118"
      Hint: Title
      Value: $name
  - Version: 2
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161128T122950Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "f311c61a-08dd-411a-b280-42e335ec6118"
      Hint: Title
      Value: $name
