---
ID: "4a86d5a3-abb0-4206-a729-2f6836ddd146"
Parent: "c2518164-6043-4d73-b26c-08d13ab49118"
Template: "c2518164-6043-4d73-b26c-08d13ab49118"
Path: /sitecore/templates/HCA/Feature/Navigation/Header/Navigation Menu/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{5DCCB05C-59F3-4579-AEA3-6E5DC934C7B0}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180428T090745Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
