---
ID: "d5e2f120-1a9f-46d3-915b-4d629caf22b0"
Parent: "54b74398-8b37-4f1c-8e59-a79cd1633d55"
Template: "54b74398-8b37-4f1c-8e59-a79cd1633d55"
Path: /sitecore/templates/HCA/Feature/Navigation/Footer/Footer Folder/__Standard Values
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: office/32x32/folder.png
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {316FF1DB-AEC1-4B16-9BBF-972F07BCEAD8}
    {C3707371-14DF-43CB-A033-9999C2A8F47E}
    {94FB0BB4-F041-45F7-A0CE-1E3899FC40E0}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200428T190125Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
