---
ID: "4ec962bf-19bb-4454-afef-7029b5c86d67"
Parent: "0cbbb134-4025-4a51-9b46-1ab7021ccb0f"
Template: "0cbbb134-4025-4a51-9b46-1ab7021ccb0f"
Path: /sitecore/templates/Wooli/Project/Wooli/Pages/Category/__Standard Values
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{3EF1A39A-6C46-47C9-A3CD-317F24FF29C8}">
        <r
          id="{7ED67F91-04A8-4312-9184-AAA36D717BB7}"
          ph="/wooli-content"
          uid="{85010786-D396-450F-99EC-400B6B4D18F3}" />
        <r
          id="{CDB952B9-FE8E-4816-AADD-DB13308E25BC}"
          ph="/wooli-content"
          uid="{8182589C-0910-484F-ABF3-EFE405374111}" />
        <r
          id="{8923317E-48A7-4A3C-80EB-AF11D35F3D9E}"
          ph="/wooli-content"
          uid="{EB7E98BD-EC89-43C4-93BB-F356561E771A}" />
        <r
          id="{1C8D57C1-E884-48CC-9E45-E8472F07BD09}"
          ph="/wooli-content/category-grid-sidebar-{8182589C-0910-484F-ABF3-EFE405374111}-0"
          uid="{F2AD7F82-ED0C-4DA5-A62A-2A1A19A977CA}" />
        <r
          id="{A7569D2D-A585-424C-B21C-74684D895B8E}"
          ph="/wooli-content/category-grid-products-{8182589C-0910-484F-ABF3-EFE405374111}-0"
          uid="{E05CDE83-B20F-456E-87B5-CE5DFD032BB3}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180425T131248Z
