---
ID: "e9b953e4-cf74-4860-a55d-2a1a7874d1eb"
Parent: "d7640afe-63c0-4cdf-876f-c17c5d3fa5c4"
Template: "d7640afe-63c0-4cdf-876f-c17c5d3fa5c4"
Path: "/sitecore/templates/CommerceConnect/Sitecore Commerce/Commerce Control Panel/Shared Settings/Countries-Regions/Countries-Regions Folder/__Standard Values"
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{1F8158D8-4139-46BE-94AF-9FF80501F5DE}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161202T071959Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
  - Version: 2
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161202T071959Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
