---
ID: "4ec962bf-19bb-4454-afef-7029b5c86d67"
Parent: "0cbbb134-4025-4a51-9b46-1ab7021ccb0f"
Template: "0cbbb134-4025-4a51-9b46-1ab7021ccb0f"
Path: /sitecore/templates/HCA/Project/HCA/Pages/Category/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {9CA4A8C4-0295-49C1-A879-E008933D0A4F}
    {0CBBB134-4025-4A51-9B46-1AB7021CCB0F}
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{3EF1A39A-6C46-47C9-A3CD-317F24FF29C8}">
        <r
          id="{7F6CAB22-D5EF-4924-AFBE-6024F6B2A758}"
          ph="/main-content"
          uid="{FCF08077-1D17-4DB4-8AE6-ED8CEAC614D0}" />
        <r
          uid="{68226758-D091-4D97-B160-31D1229247AF}"
          id="{3EA546E2-0E49-40A6-A1FC-AF7619983DB6}"
          ph="/main-content/header-content-{FCF08077-1D17-4DB4-8AE6-ED8CEAC614D0}-0" />
        <r
          uid="{4EBE8CF1-C85E-4E94-AAB6-91FA3C690BA4}"
          id="{3EA546E2-0E49-40A6-A1FC-AF7619983DB6}"
          ph="/main-content/header-content-{FCF08077-1D17-4DB4-8AE6-ED8CEAC614D0}-0" />
        <r
          uid="{760E5700-E3B9-4E04-9ABC-54328F9634DF}"
          ds="{FA351DC2-26EF-4196-9DFA-11DD5BE79DE9}"
          id="{123FE93B-8360-44DB-B660-C9D472024809}"
          par=""
          ph="/main-content/navigation-content-{FCF08077-1D17-4DB4-8AE6-ED8CEAC614D0}-0" />
        <r
          uid="{8227DAA4-549A-4DD6-8422-134A23D56D3E}"
          id="{123FE93B-8360-44DB-B660-C9D472024809}"
          ph="/main-content/header-content-{FCF08077-1D17-4DB4-8AE6-ED8CEAC614D0}-0/navigation-content-{4EBE8CF1-C85E-4E94-AAB6-91FA3C690BA4}-0" />
        <r
          uid="{DE519120-CAC4-47CA-B132-4C2DE8367CE2}"
          id="{520A7D2B-E6CA-4049-AB88-735D626B78CE}"
          ph="/main-content/header-content-{FCF08077-1D17-4DB4-8AE6-ED8CEAC614D0}-0/navigation-content-{4EBE8CF1-C85E-4E94-AAB6-91FA3C690BA4}-0" />
        <r
          uid="{06A37830-2904-4F4E-819B-26B6F631C2E8}"
          id="{4A976F66-B69F-4AF3-9E43-86FBD6E0041B}"
          ph="/main-content/header-content-{FCF08077-1D17-4DB4-8AE6-ED8CEAC614D0}-0/navigation-content-{4EBE8CF1-C85E-4E94-AAB6-91FA3C690BA4}-0" />
        <r
          uid="{81A550A2-9194-420B-A3CD-E37CA90006E3}"
          id="{B7AA5501-B17F-4896-A70F-AA8866909E99}"
          ph="/main-content/header-content-{FCF08077-1D17-4DB4-8AE6-ED8CEAC614D0}-0/navigation-content-{68226758-D091-4D97-B160-31D1229247AF}-0" />
        <r
          uid="{A5BED5B3-EE5E-4281-86A7-076450113EE1}"
          id="{7BD6038E-AFA9-4A5D-B0B4-DAF4F013B39D}"
          ph="/main-content/header-content-{FCF08077-1D17-4DB4-8AE6-ED8CEAC614D0}-0/navigation-content-{68226758-D091-4D97-B160-31D1229247AF}-0" />
        <r
          uid="{B7DACA2F-69DB-4F3D-8EC0-48915DC150C5}"
          id="{A7569D2D-A585-424C-B21C-74684D895B8E}"
          ph="/main-content/w-col-2-{AFC091B2-7B99-45B6-8E30-0C96736C326C}-0" />
        <r
          uid="{A5627BAA-8BE7-44E0-8ED3-C75983331214}"
          id="{1C8D57C1-E884-48CC-9E45-E8472F07BD09}"
          ph="/main-content/w-col-1-{AFC091B2-7B99-45B6-8E30-0C96736C326C}-0" />
        <r
          uid="{AFC091B2-7B99-45B6-8E30-0C96736C326C}"
          ds=""
          id="{B2EDE051-9A8B-4502-9D6B-39759BCFF123}"
          par="Wrapper Class=hca&amp;First Column Class=col-md-2&amp;Second Column Class=col-md-10&amp;Third Column Class"
          ph="main-content" />
        <r
          id="{9ABF5775-C231-4918-9F03-C8193D7D2C0C}"
          ph="/main-content"
          uid="{0EF78618-639B-4F26-BAE3-5E1FB33BC7BC}" />
        <r
          ds="{C5FE58AA-6401-4932-871F-D0D6623DCE5E}"
          id="{2B2AABC0-81F7-4893-B53A-A3E26B3D6663}"
          par=""
          ph="/main-content/footer-content-{0EF78618-639B-4F26-BAE3-5E1FB33BC7BC}-0/w-col-1-{8B7D9E49-DC8D-45B9-81C8-3C010932EFC4}-0/w-col-3-{70B51ADE-3E72-4024-A876-80545621B913}-0"
          uid="{F7CE6546-3AB3-4AB4-A1A8-30B22ED7E1A9}" />
        <r
          ds="{D2ABF6D8-C766-4BC0-8886-F47BA96D6E7D}"
          id="{2B2AABC0-81F7-4893-B53A-A3E26B3D6663}"
          par=""
          ph="/main-content/footer-content-{0EF78618-639B-4F26-BAE3-5E1FB33BC7BC}-0/w-col-1-{8B7D9E49-DC8D-45B9-81C8-3C010932EFC4}-0/w-col-2-{70B51ADE-3E72-4024-A876-80545621B913}-0"
          uid="{AE940294-F2FC-475E-A355-E447CB2A700A}" />
        <r
          ds="{90ED0DAB-5084-4C63-B93F-98DA30098D24}"
          id="{2B2AABC0-81F7-4893-B53A-A3E26B3D6663}"
          par=""
          ph="/main-content/footer-content-{0EF78618-639B-4F26-BAE3-5E1FB33BC7BC}-0/w-col-1-{8B7D9E49-DC8D-45B9-81C8-3C010932EFC4}-0/w-col-1-{70B51ADE-3E72-4024-A876-80545621B913}-0"
          uid="{53743A27-5901-41EA-91E6-D2169A193C70}" />
        <r
          id="{0D3A817B-862A-42E8-A71E-55A3C7A53CAF}"
          ph="/main-content/footer-content-{0EF78618-639B-4F26-BAE3-5E1FB33BC7BC}-0/w-col-1-{8B7D9E49-DC8D-45B9-81C8-3C010932EFC4}-0"
          uid="{70B51ADE-3E72-4024-A876-80545621B913}" />
        <r
          ds="{3FFA3BC6-1E9A-4EFE-92E8-B71D74E98E45}"
          id="{EFAA6F19-1DEC-4AA8-A5AE-131F7D49E7E6}"
          par=""
          ph="/main-content/footer-content-{0EF78618-639B-4F26-BAE3-5E1FB33BC7BC}-0/w-col-2-{8B7D9E49-DC8D-45B9-81C8-3C010932EFC4}-0"
          uid="{FB9345E4-2D5C-45D4-AA34-FFF30DDF0366}" />
        <r
          ds=""
          id="{129348AA-2485-482F-A0F6-B53F6C585712}"
          par="Wrapper Class=footer-columns&amp;First Column Class&amp;Second Column Class&amp;Third Column Class"
          ph="/main-content/footer-content-{0EF78618-639B-4F26-BAE3-5E1FB33BC7BC}-0"
          uid="{8B7D9E49-DC8D-45B9-81C8-3C010932EFC4}" />
        <r
          ds="{4A5CDED3-9B6E-4C1F-8E61-B871B082D783}"
          id="{F6DB8B49-C6A1-4BE9-9EE7-BD7AA0FB6E50}"
          par=""
          ph="/main-content/footer-content-{0EF78618-639B-4F26-BAE3-5E1FB33BC7BC}-0"
          uid="{8A675429-673A-4837-ACB9-D3E729B137DA}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180425T131248Z
