---
ID: "8586e179-cd31-42f7-8315-153bb95a5e55"
Parent: "3f2dcd1f-1966-4192-a279-ac6b7397bdbb"
Template: "3f2dcd1f-1966-4192-a279-ac6b7397bdbb"
Path: /sitecore/templates/CommerceConnect/Sitecore Commerce/Commerce Control Panel/Shared Settings/Fulfillment/Fulfillment Option Types Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{389AC363-2868-4180-8A70-8CE1C57D2223}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161206T105242Z
  - Version: 2
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161206T105242Z
